In [9]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\shahd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\shahd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\shahd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\shahd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\shahd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import requests
import pandas as pd
import datetime
import numpy as np

In [11]:
cities = [
    "Cairo", "Giza", "Alexandria", "Port Said", "Suez", "Ismailia",
    "Mansoura", "Tanta", "Luxor", "Aswan",
]

In [12]:
url = 'https://api.openweathermap.org/data/2.5/weather'
params = {
    'appid' : '6a13e61e853763292101962a026aa3e8',
    "q": 'Alexandria'
}
response = requests.get(url, params=params)
data = response.json()

In [13]:
print(data)

{'coord': {'lon': 29.9553, 'lat': 31.2156}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'base': 'stations', 'main': {'temp': 294.13, 'feels_like': 294.06, 'temp_min': 294.13, 'temp_max': 294.13, 'pressure': 1016, 'humidity': 68, 'sea_level': 1016, 'grnd_level': 1016}, 'visibility': 10000, 'wind': {'speed': 1.54, 'deg': 170}, 'rain': {'1h': 0.16}, 'clouds': {'all': 11}, 'dt': 1790977125, 'sys': {'type': 1, 'id': 2511, 'country': 'EG', 'sunrise': 1790999686, 'sunset': 1791042218}, 'timezone': 10800, 'id': 361058, 'name': 'Alexandria', 'cod': 200}

In [15]:
from datetime import datetime
list_cities = [] 
ingestion_time = datetime.now()
Country = 'EG'

for city in cities:
   
    params = {
    'appid' : '6a13e61e853763292101962a026aa3e8',
    "q": f"{city},EG"    }

    response = requests.get(url, params=params)
    data = response.json()


    Latitude = data['coord']['lat']
    Longitude = data['coord']['lon']
    WeatherMain = data['weather'][0]['main']
    WeatherDescription = data['weather'][0]['description']
    Temperature = data['main']['temp']
    Pressure = data['main']['pressure']
    Humidity  = data['main']['humidity']
    WindSpeed = data['wind']['speed']
    TempMin = data['main']['temp_min']
    TempMax = data['main']['temp_max']
    WindDeg = data['wind']['deg']
    Cloudiness = data['clouds']['all']
    Visibility = data['visibility']
    Sunrise = data['sys']['sunrise']
    Sunset = data['sys']['sunset']
    

    list_cities.append({
        'City': city,
        'Country': Country,
        'Latitude': Latitude,
        'Longitude': Longitude,
        'Temperature': Temperature,
        'TempMin': TempMin,
        'TempMax': TempMax,
        'Pressure': Pressure,
        'Humidity': Humidity,
        'Cloudiness': Cloudiness,
        'Visibility': Visibility,
        'WeatherMain': WeatherMain,
        'WeatherDescription': WeatherDescription,
        'WindSpeed': WindSpeed,
        'WindDeg': WindDeg,
        'Sunrise': Sunrise,
        'Sunset': Sunset,
        'IngestionTime': ingestion_time
    
    })

In [30]:
df = pd.DataFrame(list_cities)
df

,City,Country,Latitude,Longitude,Temperature,TempMin,TempMax,Pressure,Humidity,Cloudiness,Visibility,WeatherMain,WeatherDescription,WindSpeed,WindDeg,Sunrise,Sunset,IngestionTime
0,Cairo,EG,30.0626,31.2497,297.57,297.27,297.57,1017,53,0,10000,Clear,clear sky,4.63,40,1790999352,1791041930,2026-10-03 00:41:02.752433
1,Giza,EG,30.0081,31.2109,297.56,297.26,297.56,1017,53,0,10000,Clear,clear sky,1.59,349,1790999361,1791041940,2026-10-03 00:41:02.752433
2,Alexandria,EG,31.2156,29.9553,294.13,294.13,294.13,1016,68,11,10000,Rain,light rain,1.54,170,1790999686,1791042218,2026-10-03 00:41:02.752433
3,Port Said,EG,31.2565,32.2841,298.14,298.14,298.14,1017,65,0,10000,Clear,clear sky,1.03,330,1790999127,1791041658,2026-10-03 00:41:02.752433
4,Suez,EG,29.9737,32.5263,295.20,295.20,295.20,1017,70,2,10000,Clear,clear sky,2.37,293,1790999044,1791041626,2026-10-03 00:41:02.752433
5,Ismailia,EG,30.6043,32.2723,295.04,295.04,295.04,1017,72,0,10000,Clear,clear sky,0.51,69,1790999117,1791041674,2026-10-03 00:41:02.752433
6,Mansoura,EG,31.0376,31.3865,293.52,293.52,293.52,1017,74,2,10000,Clear,clear sky,1.22,223,1790999339,1791041878,2026-10-03 00:41:02.752433
7,Tanta,EG,30.7885,31.0019,294.11,294.11,294.11,1017,70,0,10000,Clear,clear sky,0.45,209,1790999426,1791041975,2026-10-03 00:41:02.752433
8,Luxor,EG,25.6989,32.6421,302.18,302.18,302.18,1017,30,43,10000,Clouds,scattered clouds,1.54,130,1790998936,1791041678,2026-10-03 00:41:02.752433
9,Aswan,EG,24.0934,32.9070,303.76,303.76,303.76,1016,30,15,10000,Clouds,few clouds,3.09,360,1790998843,1791041644,2026-10-03 00:41:02.752433

In [17]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\Users\shahd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\shahd\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import sqlalchemy

In [19]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\Users\shahd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\Users\shahd\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\shahd\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sqlalchemy import create_engine
engine = create_engine(
    "mssql+pyodbc://localhost/weather_dwh2"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
    "&TrustServerCertificate=yes"
)

In [23]:
df['LoadTime'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

In [29]:
df.head(10)

Empty DataFrame
Columns: [City, Country, Latitude, Longitude, Temperature, TempMin, TempMax, Pressure, Humidity, Cloudiness, Visibility, WeatherMain, WeatherDescription, WindSpeed, WindDeg, Sunrise, Sunset, IngestionTime]
Index: []

In [25]:
df.to_sql(
    'weather', 
    con=engine,
    schema='bronze', 
    if_exists='append', 
    index=False)

10

In [26]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://localhost/weather_dwh2"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
    "&TrustServerCertificate=yes"
)

In [27]:
df = pd.read_sql("""
    SELECT *
    FROM bronze.Bronze_WeatherData
    WHERE IngestionTime = (SELECT MAX(IngestionTime) FROM bronze.Bronze_WeatherData)
""", con=engine)

In [31]:
for col in ['Temperature', 'TempMin', 'TempMax']:
    df[col] = (df[col] - 273.15).round(2)

df[['City', 'Temperature', 'TempMin', 'TempMax']]

         City  Temperature  TempMin  TempMax
0       Cairo        24.42    24.12    24.42
1        Giza        24.41    24.11    24.41
2  Alexandria        20.98    20.98    20.98
3   Port Said        24.99    24.99    24.99
4        Suez        22.05    22.05    22.05
5    Ismailia        21.89    21.89    21.89
6    Mansoura        20.37    20.37    20.37
7       Tanta        20.96    20.96    20.96
8       Luxor        29.03    29.03    29.03
9       Aswan        30.61    30.61    30.61

In [32]:
df['City'] = df['City'].str.strip().str.title()
df['WeatherDescription'] = df['WeatherDescription'].str.strip().str.title()

region_map = {
    'Cairo': 'Greater Cairo',
    'Giza': 'Greater Cairo',
    'Alexandria': 'North Coast',
    'Port Said': 'Canal',
    'Suez': 'Canal',
    'Ismailia': 'Canal',
    'Mansoura': 'Lower Egypt',
    'Tanta': 'Lower Egypt',
    'Luxor': 'Upper Egypt',
    'Aswan': 'Upper Egypt'
}
df['Region'] = df['City'].map(region_map).fillna('Unknown')

df[['City', 'Region']]

         City         Region
0       Cairo  Greater Cairo
1        Giza  Greater Cairo
2  Alexandria    North Coast
3   Port Said          Canal
4        Suez          Canal
5    Ismailia          Canal
6    Mansoura    Lower Egypt
7       Tanta    Lower Egypt
8       Luxor    Upper Egypt
9       Aswan    Upper Egypt

In [33]:
df['TemperatureCategory'] = np.select(
    [df['Temperature'] < 15, df['Temperature'] <= 30],
    ['Cold', 'Moderate'],
    default='Hot'
)

df['HumidityCategory'] = np.select(
    [df['Humidity'] < 40, df['Humidity'] <= 70],
    ['Low', 'Medium'],
    default='High'
)

df['CloudCategory'] = np.select(
    [df['Cloudiness'] <= 25, df['Cloudiness'] <= 70],
    ['Clear', 'Partly Cloudy'],
    default='Cloudy'
)

df[['City', 'Temperature', 'TemperatureCategory', 'Humidity', 'HumidityCategory']]

         City  Temperature TemperatureCategory  Humidity HumidityCategory
0       Cairo        24.42            Moderate        53           Medium
1        Giza        24.41            Moderate        53           Medium
2  Alexandria        20.98            Moderate        68           Medium
3   Port Said        24.99            Moderate        65           Medium
4        Suez        22.05            Moderate        70           Medium
5    Ismailia        21.89            Moderate        72             High
6    Mansoura        20.37            Moderate        74             High
7       Tanta        20.96            Moderate        70           Medium
8       Luxor        29.03            Moderate        30              Low
9       Aswan        30.61                 Hot        30              Low

In [34]:
df = df.rename(columns={'WindSpeed': 'WindSpeed_ms'})
df['WindSpeed_kmh'] = (df['WindSpeed_ms'] * 3.6).round(2)
df['Visibility_km'] = (df['Visibility'] / 1000).round(2)

directions = ['North','North_East','East','South_East','South','South_West','West','North_West']
df['WindDirection'] = df['WindDeg'].apply(
    lambda d: directions[int(((d + 22.5) % 360) // 45)] if pd.notnull(d) else None
)

df[['City', 'WindSpeed_ms', 'WindSpeed_kmh', 'WindDeg', 'WindDirection', 'Visibility_km']]

,City,WindSpeed_ms,WindSpeed_kmh,WindDeg,WindDirection,Visibility_km
0,Cairo,4.63,16.67,40,North_East,10.0
1,Giza,1.59,5.72,349,North,10.0
2,Alexandria,1.54,5.54,170,South,10.0
3,Port Said,1.03,3.71,330,North_West,10.0
4,Suez,2.37,8.53,293,North_West,10.0
5,Ismailia,0.51,1.84,69,East,10.0
6,Mansoura,1.22,4.39,223,South_West,10.0
7,Tanta,0.45,1.62,209,South_West,10.0
8,Luxor,1.54,5.54,130,South_East,10.0
9,Aswan,3.09,11.12,360,North,10.0

In [35]:
for col in ['Sunrise', 'Sunset']:
    df[col] = (pd.to_datetime(df[col], unit='s', utc=True)
                 .dt.tz_convert('Africa/Cairo')
                 .dt.tz_localize(None))

df['DaylightHours'] = ((df['Sunset'] - df['Sunrise']).dt.total_seconds() / 3600).round(2)

df[['City', 'Sunrise', 'Sunset', 'DaylightHours']]

         City             Sunrise              Sunset  DaylightHours
0       Cairo 2026-10-03 06:49:12 2026-10-03 18:38:50          11.83
1        Giza 2026-10-03 06:49:21 2026-10-03 18:39:00          11.83
2  Alexandria 2026-10-03 06:54:46 2026-10-03 18:43:38          11.81
3   Port Said 2026-10-03 06:45:27 2026-10-03 18:34:18          11.81
4        Suez 2026-10-03 06:44:04 2026-10-03 18:33:46          11.83
5    Ismailia 2026-10-03 06:45:17 2026-10-03 18:34:34          11.82
6    Mansoura 2026-10-03 06:48:59 2026-10-03 18:37:58          11.82
7       Tanta 2026-10-03 06:50:26 2026-10-03 18:39:35          11.82
8       Luxor 2026-10-03 06:42:16 2026-10-03 18:34:38          11.87
9       Aswan 2026-10-03 06:40:43 2026-10-03 18:34:04          11.89

In [36]:
df['LoadTime'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

In [37]:
silver_cols = ['City','Country','Latitude','Longitude','Temperature','TempMin',
               'TempMax','Pressure','Humidity','Cloudiness','CloudCategory',
               'Visibility_km','WindSpeed_ms','WindSpeed_kmh','WindDeg',
               'WindDirection','WeatherMain','WeatherDescription','Sunrise',
               'Sunset','DaylightHours','Region','TemperatureCategory',
               'HumidityCategory','IngestionTime']

df_silver = df[silver_cols]

In [38]:
df_silver.to_sql(
    "Silver_WeatherData",     
    engine,
    schema="silver",
    if_exists="append",
    index=False
)

10

In [39]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

engine = create_engine(
    "mssql+pyodbc://localhost/weather_dwh2"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
    "&TrustServerCertificate=yes"
)

df = pd.read_sql("""
    SELECT *
    FROM silver.Silver_WeatherData
    WHERE IngestionTime = (SELECT MAX(IngestionTime) FROM silver.Silver_WeatherData)
""", con=engine)

In [40]:
df['TempRange'] = (df['TempMax'] - df['TempMin']).round(2)
print(df[['City', 'TempMin', 'TempMax', 'TempRange']])

         City  TempMin  TempMax  TempRange
0       Cairo    24.12    24.42        0.3
1        Giza    24.11    24.41        0.3
2  Alexandria    20.98    20.98        0.0
3   Port Said    24.99    24.99        0.0
4        Suez    22.05    22.05        0.0
5    Ismailia    21.89    21.89        0.0
6    Mansoura    20.37    20.37        0.0
7       Tanta    20.96    20.96        0.0
8       Luxor    29.03    29.03        0.0
9       Aswan    30.61    30.61        0.0

In [42]:
T = df['Temperature']
H = df['Humidity']

df['HeatIndex'] = (
    T + 0.33 * (H / 100 * 6.105 * np.exp(17.27 * T / (237.7 + T))) - 4.0
).round(2)

print(df[['City', 'Temperature', 'Humidity', 'HeatIndex']])

         City  Temperature  Humidity  HeatIndex
0       Cairo        24.42        53      25.76
1        Giza        24.41        53      25.74
2  Alexandria        20.98        68      22.54
3   Port Said        24.99        65      27.76
4        Suez        22.05        70      24.16
5    Ismailia        21.89        72      24.11
6    Mansoura        20.37        74      22.20
7       Tanta        20.96        70      22.68
8       Luxor        29.03        30      28.99
9       Aswan        30.61        30      30.94

In [43]:
df['WindCategory'] = np.select(
    [df['WindSpeed_kmh'] < 12, df['WindSpeed_kmh'] <= 30],
    ['Calm', 'Breezy'],
    default='Windy'
)
print(df[['City', 'WindSpeed_kmh', 'WindCategory']])

         City  WindSpeed_kmh WindCategory
0       Cairo          16.67       Breezy
1        Giza           5.72         Calm
2  Alexandria           5.54         Calm
3   Port Said           3.71         Calm
4        Suez           8.53         Calm
5    Ismailia           1.84         Calm
6    Mansoura           4.39         Calm
7       Tanta           1.62         Calm
8       Luxor           5.54         Calm
9       Aswan          11.12         Calm

In [44]:
temp_penalty = (df['Temperature'] - 24).abs() * 4
hum_penalty  = (df['Humidity'] - 50).abs() * 0.5

df['ComfortScore'] = (100 - temp_penalty - hum_penalty).clip(0, 100).round(1)

df['ComfortCategory'] = np.select(
    [df['ComfortScore'] >= 75, df['ComfortScore'] >= 50],
    ['Comfortable', 'Acceptable'],
    default='Uncomfortable'
)
print(df[['City', 'Temperature', 'Humidity', 'ComfortScore', 'ComfortCategory']])

         City  Temperature  Humidity  ComfortScore ComfortCategory
0       Cairo        24.42        53          96.8     Comfortable
1        Giza        24.41        53          96.9     Comfortable
2  Alexandria        20.98        68          78.9     Comfortable
3   Port Said        24.99        65          88.5     Comfortable
4        Suez        22.05        70          82.2     Comfortable
5    Ismailia        21.89        72          80.6     Comfortable
6    Mansoura        20.37        74          73.5      Acceptable
7       Tanta        20.96        70          77.8     Comfortable
8       Luxor        29.03        30          69.9      Acceptable
9       Aswan        30.61        30          63.6      Acceptable

In [45]:
df['TempRank'] = df['Temperature'].rank(ascending=False, method='min').astype(int)
print(df[['City', 'Temperature', 'TempRank']].sort_values('TempRank'))

         City  Temperature  TempRank
9       Aswan        30.61         1
8       Luxor        29.03         2
3   Port Said        24.99         3
0       Cairo        24.42         4
1        Giza        24.41         5
4        Suez        22.05         6
5    Ismailia        21.89         7
2  Alexandria        20.98         8
7       Tanta        20.96         9
6    Mansoura        20.37        10

In [46]:
df['WeatherDate'] = df['IngestionTime'].dt.date
df['WeatherHour'] = df['IngestionTime'].dt.hour

In [47]:
gold_cols = ['City','Country','Latitude','Longitude','Temperature','TempMin',
             'TempMax','TempRange','HeatIndex','Pressure','Humidity','Cloudiness',
             'CloudCategory','Visibility_km','WindSpeed_ms','WindSpeed_kmh',
             'WindCategory','WindDeg','WindDirection','WeatherMain',
             'WeatherDescription','Sunrise','Sunset','DaylightHours',
             'Region','TemperatureCategory','HumidityCategory','ComfortScore',
             'ComfortCategory','TempRank','WeatherDate','WeatherHour',
             'IngestionTime']

df_gold = df[gold_cols]

In [48]:
with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE gold.Gold_WeatherData"))

df_gold.to_sql("Gold_WeatherData", engine, schema="gold",
               if_exists="append", index=False)

10